"""Auto-update migration

Revision ID: 0f3c64d9d1e2
Revises: c49df0d07437
Create Date: 2025-02-07 21:39:21.571585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3c64d9d1e2'
down_revision: Union[str, None] = 'c49df0d07437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
