"""Auto-update migration

Revision ID: 1b4dd9a591bf
Revises: c374c5dad187
Create Date: 2025-02-07 22:49:14.486285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b4dd9a591bf'
down_revision: Union[str, None] = 'c374c5dad187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_explanation_versions_id', table_name='explanation_versions')
    op.drop_index('ix_explanation_versions_scale_name', table_name='explanation_versions')
    op.drop_index('ix_explanation_versions_version_number', table_name='explanation_versions')
    op.drop_table('explanation_versions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('explanation_versions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scale_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('examples', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='explanation_versions_pkey')
    )
    op.create_index('ix_explanation_versions_version_number', 'explanation_versions', ['version_number'], unique=False)
    op.create_index('ix_explanation_versions_scale_name', 'explanation_versions', ['scale_name'], unique=False)
    op.create_index('ix_explanation_versions_id', 'explanation_versions', ['id'], unique=False)
    # ### end Alembic commands ###
