"""Auto-update migration

Revision ID: 57a6b9c8dc5c
Revises: aabe455657cb
Create Date: 2025-02-13 01:04:14.863650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a6b9c8dc5c'
down_revision: Union[str, None] = 'aabe455657cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
