"""Auto-update migration

Revision ID: 7ace8a9bcfb1
Revises: 0e4d9112a94a
Create Date: 2025-02-07 21:29:09.112589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ace8a9bcfb1'
down_revision: Union[str, None] = '0e4d9112a94a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
