version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/api.env
    command: [ "python3", "/app/entrypoint_dev.py" ]
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - rabbitmq
      - feedback-postgres

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/worker.env
    command: [ "python3", "/app/entrypoint_dev.py" ]
    depends_on:
      - rabbitmq
      - feedback-postgres
    volumes:
      - ./backend:/app

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - ./backend/rabbitmq.env
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"

  feedback-postgres:
    image: postgres:latest
    env_file:
      - ./backend/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis-cache:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
